# Generated by Django 3.2 on 2023-06-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ticker', models.CharField(max_length=500)),
                ('link_to_video', models.CharField(max_length=500)),
            ],
        ),
    ]
