# Generated by Django 3.2 on 2023-06-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerVideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'verbose_name': 'Бегущая строка', 'verbose_name_plural': 'Бегущие строки'},
        ),
        migrations.AlterField(
            model_name='ticker',
            name='link_to_video',
            field=models.CharField(max_length=500, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='text_ticker',
            field=models.CharField(max_length=500, verbose_name='Текст бегущей строки'),
        ),
    ]
